### ISSUE TITLE
Changing avatar borks when the URL given has parameters.

### ISSUE THREAD

**Issue by clickbait** [iEquinox-/PythoBB#5]
![image](http://noscope.me/i/2014-12-08_2138.png)
When the given URL has parameters, an error occurs.

**Comment by iEquinox-** [comment]
This is because of the way PythoBB checks avatars for allowed extensions.
http://i.imgur.com/n74XITE.png
I should have used regex, but a good portion of PythoBB was written when I was in a lazy phase. This will be updated soon.
